### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by mariano-meitre** [infinitered/nsfwjs#118]
How hard will be to use or port this to React Native? Right now, the content analyzed is based on a DOM node. But maybe there's a way to pass an image/video URL or a base64 to analyze?

**Comment by GantMan** [comment]
### I'd love for this to work with React Native

The big issue right now is that TFJS doesn't work with RN.   You COULD however, use a webview (hah!) and take the results and report them back to RN!

I've heard from Google they hope to support RN at some point, but that will be a while.

**Comment by kevinvangelder** [comment]
@mariano-meitre Good news! https://twitter.com/tafsiri/status/1169312345358815233

**Comment by kevinvangelder** [comment]
There are some rough edges, but it is now possible to use NSFWJS in a React Native app. https://shift.infinite.red/nsfw-js-for-react-native-a37c9ba45fe9
