### ISSUE TITLE
Invalid mode.json file

### ISSUE THREAD

**Issue by sasikanth513** [infinitered/nsfwjs#119]
To host model on our own server in readme.md you've provided link to https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model

I was trying to host these on my server and was facing issues but working absolutely fine with the default files then figured out that `model.json` from `demo` folder is different from the one you're using as default here `https://s3.amazonaws.com/ir_public/nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/model.json`

happy to send pull request, if you can confirm that is the issue.

**Comment by sasikanth513** [comment]
Also in the paths section of the hosted `model.json` you only have one path which is `group1-shard1of1` but in github in demo folder there are 6 paths

```
"paths": [
"group1-shard1of6",
"group1-shard2of6",
"group1-shard3of6",
"group1-shard4of6",
"group1-shard5of6",
"group1-shard6of6"
],
```

which one is valid and which one gives more accurate results?

**Comment by GantMan** [comment]
I've created two models now.

One that is very small that is 90% accurate, and one that is 23MB large, but is 93% accurate.

You can see that I've added this to the main site:
![image](https://user-images.githubusercontent.com/997157/60608313-c651bc00-9d84-11e9-925a-0c863ea2a888.png)


Any updates to the readme/docs would be greatly appreciated!!!

**Comment by plzgix123** [comment]
у меня всё работает
