### ISSUE TITLE
Classifying Image data?

### ISSUE THREAD

**Issue by Bengejd** [infinitered/nsfwjs#128]
I was curious about the capabilities of NSFWJS, when it came to classifying Image data, instead of an actual element. In the **Parameters** of **ClassifyImage**, it states: 

> Tensor, Image data, Image element, video element, or canvas element to check

So does that mean I could potentially pass an images base64 data to NSFWJS, and it would render the results, or does it have to be the actual image element itself?

I'm just curious about the applications of this, and how it could be used server side.

**Comment by GantMan** [comment]
Basically, I get to use the awesomeness of Tensorflow JS here.

Whatever TFJS can convert, NSFWJS can read.   The Image data portion is the web ImageData (https://developer.mozilla.org/en-US/docs/Web/API/ImageData)

Here's some good info on reading base64 encoding:  https://github.com/tensorflow/tfjs/issues/1485

**Comment by Bengejd** [comment]
Awesome, I figured it could take the image data, I was mainly looking for a confirmation of it. Thanks!
