### ISSUE TITLE
Using without third-party server?

### ISSUE THREAD

**Issue by Chinafreak** [infinitered/nsfwjs#139]
Is there any way to use this offline aka do not use from your S3 server? Maybe there is a way to download the existing trained data on your server which can be used at offline. 

Why? It could be complicated due DSGVO and the less there are third party servers, the less complicated it gets. 😄 or am I missing here?

**Comment by GantMan** [comment]
Yes! You can host the files locally on your site, computer, cache etc.  You can download them and point the code to load models from anywhere.

See here:  https://github.com/infinitered/nsfwjs#load-the-model

**Comment by Chinafreak** [comment]
Thanks for fast reply! Sound good. Where can I download the existing trained data? 👏

**Comment by GantMan** [comment]
The large one 93% accurate can be found here:  https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model

The smaller one 90% accurate but 1/10th the size here:
https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/quant_nsfw_mobilenet

These are the two folder I use for NSFWJS.com - neither uses our S3

**Comment by Chinafreak** [comment]
Great, thank you so much 😄 One last question, do I only need the .json file or also this "group1_shardXof6" too?

**Comment by Chinafreak** [comment]
Ah it does. Ok, got everything what I have. Thanks for the project! 👏 I'm going to have fun experiments with them.
