### ISSUE TITLE
Crash on Mobile Safari

### ISSUE THREAD

**Issue by tabrindle** [infinitered/nsfwjs#15]
When taking a picture to check on iOS 12.1.3, the webpage crashes.

Loading from the camera roll works fine.

**Comment by GantMan** [comment]
Good to know!  I might have an experiment for you to check if it's the image capture on the ML portion.

Thanks for reporting this!

**Comment by GantMan** [comment]
Unable to recreate for now, so closing.  Reopen if you can give me a reproducible way to make this happen.
