### ISSUE TITLE
Change `load()` to accept a model instead of a string path

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/nsfwjs#170]
In platforms other than web, simply passing a string path to the model won't work. Instead, we should rely on the developer consuming NSFWjs to require the model and pass it in to `load()`.

**Comment by GantMan** [comment]
right now it takes a PathIO object as well.  Maybe @mlaco who added this might be able to join in.

OR maybe it should handle a string to a local file path?

**Comment by arifszn** [comment]
How can I load the model from the `src` folder instead of `public` folder in a react project?

**Comment by GantMan** [comment]
That makes sense.  From what I've read, importing from src simply gives you the string value anyway though.

So the code below pulls from source, but gives the rendered string of the dynamic object.
```ts
import React from 'react';
import logo from './logo.png'; // Tell webpack this JS file uses this image

console.log(logo); // /logo.84287d09.png
```

Shouldn't that work?

**Comment by arifszn** [comment]
@GantMan But the problem is that the load method accepts the folder path instead of the file path.

https://stackblitz.com/edit/react-c4416f?file=src%2FApp.js

I will submit a PR for this.

**Comment by GantMan** [comment]
Can you test against master and if everything is OK I'll push a new minor version release?

**Comment by GantMan** [comment]
k.  Sounds good.  I think I need to do some significant upgrades to dependencies to get CRA 5 working.  I need to add polyfills.  I started looking into this at one point but it's a complex upgrade.

**Comment by arifszn** [comment]
Any ETA when we can expect the update on NPM for the file path?

**Comment by arifszn** [comment]
Ping @GantMan.

**Comment by GantMan** [comment]
yarn test is failing for some reason - which is stopping the release.  I'll look into it.
