### ISSUE TITLE
Pre-trained model link is dead

### ISSUE THREAD

**Issue by antoinechampion** [infinitered/nsfwjs#172]
When downloading the model through the s3 at https://s3.amazonaws.com/ir_public/nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/ 

The following error code is thrown:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/
</Key>
<RequestId>8ECD5C58025A96EC</RequestId>
<HostId>
0wNKLqrKG2SyXYZ4d//i3otFu2uOq+OE7xEQkACROa/HRY/+vfIINBlAqG3oYATZbUVxtFoz44A=
</HostId>
</Error>
```

**Comment by GantMan** [comment]
add model.json

https://s3.amazonaws.com/ir_public/nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/model.json
