### ISSUE TITLE
Cannot read property 'filterHeight' of undefined

### ISSUE THREAD

**Issue by tallongsun** [infinitered/nsfwjs#180]
hello~ i'm new to nsfwjs.  when i run minimal_demo program on chrome, i got the following error. 
> Uncaught (in promise) TypeError: Cannot read property 'filterHeight' of undefined.  

Anyone can help me?

**Comment by GantMan** [comment]
Thansk for catching this!  It looks like a mixup was happening btw TF and NSFWJS

I've fixed this by locking versions.  Please pull latest from master.
