### ISSUE TITLE
Where is the FAQ?

### ISSUE THREAD

**Issue by mifi** [infinitered/nsfwjs#196]
https://github.com/infinitered/nsfwjs/wiki/FAQ redirects to home page

**Comment by GantMan** [comment]
@jamonholmgren - is wiki turned off for our org?   I had a WIKI setup and now it's gone.  Not only is it gone, I can't seem to find the wikipage link!   I can find one in my personal GitHub.   So I'm at a bit of a loss of where the wiki went.

It held some pretty critical info.

**Comment by GantMan** [comment]
UPDATE:  It was turned off.... by whom I have no clue!

I turned it back on in settings.   
![image](https://user-images.githubusercontent.com/997157/68273490-32427a80-002c-11ea-8abd-763f534d4c5e.png)


Sorry @mifi - looks like it's back now, and still contained all the important data.
