### ISSUE TITLE
Training on Submitted Images

### ISSUE THREAD

**Issue by nathanielcwm** [infinitered/nsfwjs#27]
IDK if this is already taking place but maybe you could use images submitted to help train the Neural Network?
Also maybe there could also be a people category.

**Comment by GantMan** [comment]
Hey hey!  So the first things first.  If you have some categories that you're identifying as mistakes, you can contribute to the scraper.
https://github.com/alexkimxyz/nsfw_data_scraper

There might be a torrent file of the training data soon.  From that torrent, there is room to clean the data and augment and organize it.

**Comment by GantMan** [comment]
Ask me or https://twitter.com/KarthikRevanuru for the key

https://mega.nz/#!Q5RnDQYa

Let me know if you make a modified training set that we could use!
