### ISSUE TITLE
Build with webpack

### ISSUE THREAD

**Issue by ghnp5** [infinitered/nsfwjs#273]
Hello,

Has anyone succeeded building NSFW.js with Webpack, that would be able to provide me with a working config?

Unfortunately, when building I get some warnings, which I'm not sure whether I can fix or not  (no errors I get), but then, when I run "node index.min.js", I get a huge output which is a partial minified JS, and then the following error:

> */var n=Object.getOwnPropertySymbols,i=Object.prototype.hasOwnProperty,o=Object.prototype.propertyIsEnumerable;function a(e){if(null==e)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}e.exports=function(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de","5"===Object.getOwnPropertyNames(e)[0])return!1;for(var t={},r=0;r<10;r++)t["_"+String.fromCharCode(r)]=r;if("0123456789"!==Object.getOwnPropertyNames(t)
> (there's a lot more code, but I truncated it for this issue)
>
> 
> Error: package.json does not exist at F:\package.json
>     at Object.t.find (F:\path\to\proj\build\index.min.js:169:11682)
>     at Object.<anonymous> (F:\path\to\proj\build\index.min.js:472:426)
>     at Object.<anonymous> (F:\path\to\proj\build\index.min.js:472:916)
>     at r (F:\path\to\proj\build\index.min.js:1:110)
>     at Object.<anonymous> (F:\path\to\proj\build\index.min.js:289:44677)
>     at r (F:\path\to\proj\build\index.min.js:1:110)
>     at F:\path\to\proj\build\index.min.js:1:902
>     at Object.<anonymous> (F:\path\to\proj\build\index.min.js:1:913)
>     at Module._compile (internal/modules/cjs/loader.js:1151:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)

I can't understand why a production build is looking for "package.json" in the root of the F:\ drive.

My webpack config:

```
module.exports = [
	{
		name: 'server',
		context: __dirname,
		entry: './index.js',
		target: 'node',
		mode: 'production',
		output: {
			path: path.resolve(__dirname, 'build'),
			filename: 'index.min.js',
		},
		module: {
			rules : [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: ['babel-loader'],
			},
			]
		},
		resolve: {
			modules: [
				path.join(__dirname, "node_modules"),
			]
		},
		node: {
			fs: 'empty', // Module not found: Error: Can't resolve 'fs'
			child_process: 'empty', // Module not found: Error: Can't resolve 'child_process'
		},
		plugins: [],
	}
];
```

**Comment by GantMan** [comment]
helpful/not helpful

NSFWJS.com is webpack under the create react app config.

I know that's like throwing a phone book at someone, but it proves it is possible.

**Comment by cdanwards** [comment]
@ghnp5 let us know if you're still having this problem, in the mean time we're closing this issue. Thanks!
