### ISSUE TITLE
Blocked ui

### ISSUE THREAD

**Issue by GZ-ted** [infinitered/nsfwjs#31]
I found ui been blocked for few seconds when execute ”nsfwjs.load('/path/to/model/directory/') “. How to optimize it?

**Comment by GantMan** [comment]
Good call, I noticed this, too.  

This block seems to be built into Tensorflow, and is very likely the fetch call.  I really don't know what's causing it, but this would be a fantastic PR if someone could find/fix this issue.

**Comment by emer7** [comment]
I opened an issue at tensorflowjs repo.
[tfjs#1373](https://github.com/tensorflow/tfjs/issues/1373)

**Comment by GantMan** [comment]
PR #78 is ready, so when that's merged, we can test this a bit more.

**Comment by GantMan** [comment]
From my testing, it looks like this is fixed in TFJS 1.x

**Comment by GantMan** [comment]
Closing this, I feel 1.x was the fix.

**Comment by danieldaeschle** [comment]
I'm on tf 1.1.0 and it still blocks the UI. Does someone knows what i can do?
