### ISSUE TITLE
video support

### ISSUE THREAD

**Issue by FunnyDevs** [infinitered/nsfwjs#32]
Hi! Are you planning to release video support? 
thanks

**Comment by GantMan** [comment]
I'll keep working on it.  Video means a few things.

* I could access the webcam and do live video realtime checking.
* I could scan a video and express if it's safe or not. 

As of right now, you can pass a video element to the detector, but I believe it will only process the first frame of the video, not all of them.

I hope to add both those features mentioned above.  Wish me luck!

**Comment by FunnyDevs** [comment]
ok, what i'm interested is second option.
Thank you for your response and for your work!

**Comment by GantMan** [comment]
I've created tickets #38 and #39 for the processing of a video.

I'll use this ticekt for live webcam video updates.   Please subscribe the others as you wish.  this ticket will be closed when Webcam support is complete (meaning the example).

**Comment by FunnyDevs** [comment]
ok, thank you!

**Comment by GantMan** [comment]
We have webcam working but it's insanely slow.  Not sure if I'll release this.

**Comment by GantMan** [comment]
Nevermind, I figured out how to fix the speed issue.  Will release soon.
