### ISSUE TITLE
Error: FileReader.readAsArrayBuffer is not implemented

### ISSUE THREAD

**Issue by JoonJoon123** [infinitered/nsfwjs#331]
Hi @GantMan @kevinvangelder ,

I tried this code in a new react native project but I was getting this error. 
I used react-native 0.61.5 and react 16.9.0 to produce this error.

[Unhandled promise rejection: Error: FileReader.readAsArrayBuffer is not implemented]
- node_modules/react-native/Libraries/Blob/FileReader.js:84:20 in readAsArrayBuffer
- node_modules/react-native/Libraries/vendor/core/whatwg-fetch.js:220:29 in readBlobAsArrayBuffer

**Comment by kevinvangelder** [comment]
Closing in favor of https://github.com/infinitered/nsfwjs-mobile/issues/9
