### ISSUE TITLE
Error: Size(200704) must match the product of shape 1,224,224,3

### ISSUE THREAD

**Issue by NorteX-dev** [infinitered/nsfwjs#336]
Hi.

I'm using the module together with NodeJS, and when I run the `model.classify(image);` function it only successfully executes for a certain portion of images (roughly 50%)

Sometimes, I get the error:
```md
Error: Size(200704) must match the product of shape 1,224,224,3
```

I have no control over what size the images are posted in (as the user sends them in whatever size), I can only resize them at max. ~~From my observations, it doesn't work for square or square-ish images, the rest seems to be ok, although I will continue my testings.~~ Edit: random images do that, not only square or square-ish

I'm using the default model: `nsfwjs.load();`

My whole code:
```js
const photoUrl = "domain.com/photo.png"; /* Note: this is only a placeholder */
const pic = await axios.get(photoUrl, { responseType: `arraybuffer` });
let model = await nsfwjs.load();
let image = await tf.node.decodeImage(pic.data);
let predictions = model.classify(image);
/* Do something with predictions */
```
(It's almost directly copied from the readme files on Github & npm)

**Comment by GantMan** [comment]
That's strange.  It should resize the images for you.

Can you assure you're using a new-ish version of TFJS?  

I'm not an expert on the Node side, as that code was written by the community.   But the concepts seem simple enough.

**Comment by NorteX-dev** [comment]
I'm using the latest version.

**Comment by GantMan** [comment]
Please create an open source repo of your example, I'll pull down the code exactly as you have it, and provide an image that fails in the demo.

This will assure I solve the exact problem as I dig in.   I'd describe my steps, but they are going to be very ML specific.   I should have an answer of what's technically breaking and if I can fix it.

**Comment by NorteX-dev** [comment]
Can't not my code.

**Comment by invalidcpp** [comment]
I had the same issue today. I went through the react native files for [https://github.com/infinitered/nsfwjs-mobile/blob/master/App.js](NSFW-JS) and found a function called imagetotensor. I used the code from that to convert my array buffer to a 3d tensor, and it seems to work pretty well for me. I am getting slight issues, but I think they might just be false positives. If anyone sees any issue with the below code please let me know :)

```javascript
var sizeOf = require('buffer-image-size'); //npm install buffer-image-size
const pic = await axios.get(photoUrl, { responseType: "arraybuffer" });
let model = await nsfwjs.load();
var dimensions = sizeOf(pic.data);
const buffer = new Uint8Array(dimensions.width * dimensions.height * 3);
let offset = 0; // offset into original data
for (let i = 0; i < buffer.length; i += 3) {
    buffer[i] = pic.data[offset];
    buffer[i + 1] = pic.data[offset + 1];
    buffer[i + 2] = pic.data[offset + 2];
    offset += 4;
}
const image = tf.tensor3d(buffer, [dimensions.height, dimensions.width, 3]);
let predictions = model.classify(image);
```
