### ISSUE TITLE
http://nsfwjs.com/ failed to load AI model

### ISSUE THREAD

**Issue by pyrosoma** [infinitered/nsfwjs#355]
I happen to find that "http://nsfwjs.com/" can't work anymore.

It seems AI model failed to load.

I am using Google Chrome 83.0.4103.97 64 bit.

**Comment by GantMan** [comment]
This is now fixed.  Thanks for the catch.

**Comment by GantMan** [comment]
When the github badge turns from this to green, please test and close the ticket.
<img width="194" alt="Screen Shot 2020-06-11 at 11 45 37 PM" src="https://user-images.githubusercontent.com/997157/84465873-b782b300-ac3d-11ea-8e77-75972d797037.png">
