### ISSUE TITLE
Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded.

### ISSUE THREAD

**Issue by willsmanley** [infinitered/nsfwjs#375]
Package works for me in development, but not on a production server. This is the error message I got and I don't know much more about it than what it says.

`Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded.`

Here is my code. It is basically the simple example on the readme but with a couple of small changes:
```
<script src="https://unpkg.com/@tensorflow/tfjs@1.2.8" type="text/javascript"></script>
<script src="https://unpkg.com/nsfwjs@2.1.0" type="text/javascript"></script>
<script>
    const img = new Image()
    // image is hosted on the same domain as this page, so no crossDomain attribute is required
    img.src = "{{$url}}"

    // Load the model.
    nsfwjs.load(
        'my/path/to/model/directory',
        { size: 299 }
    ).then(model => {

        // Classify the image.
        model.classify(img).then(predictions => {
             // changed from console log to document write
            document.write(JSON.stringify(predictions));
        })

    })
</script>
<body>
</body>

```

**Comment by GantMan** [comment]
It sounds to me like you might have CORS or some other cross origin protection in place.

Try setting `img.crossOrigin = "anonymous";`

**Comment by willsmanley** [comment]
Looks like you were right on that one. I had too many problems with CORS settings, especially when handling images from unknown sites. So switching to a Node.js configuration made it a lot more predictable
