### ISSUE TITLE
Run on every frame inside a GIF

### ISSUE THREAD

**Issue by GantMan** [infinitered/nsfwjs#38]
Currently only one frame is selected.  Whatever was visible when the classification was run.

Better to grab all frames from a gif:

Use this library: https://github.com/buzzfeed/libgif-js

Here's an example of grabbing all frames
https://jsfiddle.net/zpmgv7k4/

The question is... How do we report this?

# Discussion portion
Do we report back the prediction on every frame?  Or do we average all the frames?  Both?

**Comment by emer7** [comment]
Hi! I found this project and sounds cool!
Just clarifying, is the gif going to be combine together again as an animated GIF?

**Comment by GantMan** [comment]
My thought, is that it would return an array of the classification of each frame of the GIF.

So if a gif has 16 frames, it returns 16 classifications.  This might be perfect, for people to set their own threshold on how many "dirty" images make the whole GIF "dirty" etc.

**Comment by fvonhoven** [comment]
@emer7 you planning on jumping on this one?

**Comment by emer7** [comment]
Oh okay, yeah I would like to try to implement this feature
