### ISSUE TITLE
NSFW Filter is released!

### ISSUE THREAD

**Issue by navendu-pottekkat** [infinitered/nsfwjs#383]
Hi Team,

We have released version 1.0.0 of NSFW Filter which was developed using nsfwjs. Thank you for your help in answering our queries. 

Now we need to get contributors to the project to improve it and add more features. If you could, give us a shout out in social media to reach more people.

@GantMan Thanks for your help!

Link: https://github.com/navendu-pottekkat/nsfw-filter

**Comment by GantMan** [comment]
https://twitter.com/FunMachineLearn/status/1288900451140808704

**Comment by navendu-pottekkat** [comment]
@GantMan That is awesome!

**Comment by GantMan** [comment]
Closing this ticket!   Really happy to see this great work.
