### ISSUE TITLE
Error when using a custom model

### ISSUE THREAD

**Issue by conver4y** [infinitered/nsfwjs#397]
> "classname" and "config" must be set.

**Comment by conver4y** [comment]
I've emailed Gantman, and please take a look at it.

**Comment by GantMan** [comment]
Can you provide a repo with your custom model so I can debug?

**Comment by conver4y** [comment]
> Can you provide a repo with your custom model so I can debug?

My code was like this:
```js
const axios = require('axios') //you can use any http client
const tf = require('@tensorflow/tfjs-node')
const nsfw = require('nsfwjs')
async function fn() {
  const pic = await axios.get(link_image, {responseType: 'arraybuffer'})
  const model = await nsfw.load("file://anti-nsfw-bot/project-model/")
  const image = await tf.node.decodeImage(pic.data,3)
  const predictions = await model.classify(image)
  image.dispose()
  console.log(predictions)
}
fn()```

I was using your newest model.
> https://github.com/GantMan/nsfw_model/releases/tag/1.2.0

**Comment by GantMan** [comment]
What version of TensorFlow js?

**Comment by conver4y** [comment]
@tensorflow/tfjs-node: 2.3.0
@tensorflow/tfjs: 2.3.0

**Comment by GantMan** [comment]
I believe that's the issue.  

I have it on my TODO to support the latest version of TFJS, but they made some breaking changes when they jumped from 1.x to 2.x and I need to come back and update it.
Try "@tensorflow/tfjs": "^1.7.4"

**Comment by conver4y** [comment]
Which one? tfjs or tfjs-node?
Also I tried to downgrade it, and it said version not found (404)

**Comment by GantMan** [comment]
tfjs

**Comment by conver4y** [comment]
![image](https://user-images.githubusercontent.com/33544674/90414713-b4df8680-e0e2-11ea-8f6b-a0e725d7add2.png)

**Comment by conver4y** [comment]
Should I use above than 1.7.4 ?

**Comment by conver4y** [comment]
**Update:**
I uninstall tfjs (not the node one)
I downgraded my node to v12.13.0
Now I only used tfjs-node v2.1.0
I don't know if I stuck at here.
**Only HTTP(S) protocols are supported**
Don't know why but I'm stuck here.

**Comment by conver4y** [comment]
Yes, I only have tfjs-node.

**Comment by qwertyforce** [comment]
@conver4y
just had the same problem
uninstall @tensorflow/tfjs-node and @tensorflow/tfjs
and then 
npm install @tensorflow/tfjs-node
npm install @tensorflow/tfjs@^1.7.4
EXACTLY IN THIS ORDER
idk why, but when I install  @tensorflow/tfjs@^1.7.4 first, it crashes with the same error you had
![image](https://user-images.githubusercontent.com/44163887/94936092-778a5900-04d6-11eb-8330-b714aaf491f4.png)

**Comment by conver4y** [comment]
> @conver4y
> I've just had the same problem
> uninstall @tensorflow/tfjs-node and @tensorflow/tfjs
> and then
> npm install @tensorflow/tfjs-node
> npm install @tensorflow/tfjs@^1.7.4
> EXACTLY IN THIS ORDER
> idk why, but when I install @tensorflow/tfjs@^1.7.4 first, it crashes with the same error you had
> ![image](https://user-images.githubusercontent.com/44163887/94936092-778a5900-04d6-11eb-8330-b714aaf491f4.png)

exactly the same dude :)

**Comment by GantMan** [comment]
I'll go ahead and close this issue.  If you can think of a proper place to warn others of this issue with install order, please PR the docs.
