### ISSUE TITLE
Add simple tests

### ISSUE THREAD

**Issue by GantMan** [infinitered/nsfwjs#4]
Currently, this is a simple node module so manual testing is easy but add some basic tests anyway.

**Comment by GantMan** [comment]
completed!

**Comment by izoyo** [comment]
Where can I get the simple demo...?

**Comment by GantMan** [comment]
The demo code is located here: https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo

And published here: https://nsfwjs.com/
