### ISSUE TITLE
Need help with model.classifyGif()

### ISSUE THREAD

**Issue by edsumpena** [infinitered/nsfwjs#436]
Hi, I'm building a server on node.js to handle NSFW gifs. However, I've run into some error messages and I'm not sure how to resolve them.

(node:4365) UnhandledPromiseRejectionWarning: Error: "url" option is required.
    at Object.gifFrames [as default] (/home/runner/HandmadeSeparateProjections/node_modules/@nsfw-filter/gif-frames/gif-frames.js:45:12)
    at NSFWJS.<anonymous> (/home/runner/HandmadeSeparateProjections/node_modules/nsfwjs/dist/index.js:204:60)
    at step (/home/runner/HandmadeSeparateProjections/node_modules/nsfwjs/dist/index.js:52:23)
    at Object.next (/home/runner/HandmadeSeparateProjections/node_modules/nsfwjs/dist/index.js:33:53)
    at /home/runner/HandmadeSeparateProjections/node_modules/nsfwjs/dist/index.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/HandmadeSeparateProjections/node_modules/nsfwjs/dist/index.js:23:12)
    at NSFWJS.classifyGif (/home/runner/HandmadeSeparateProjections/node_modules/nsfwjs/dist/index.js:193:16)
    at Client.<anonymous> (/home/runner/HandmadeSeparateProjections/index.js:1800:38)

So here's what I have done:

```
const pic = await axios.get(linkToGif, {
              responseType: 'arraybuffer',
})     // Get the GIF in the form of a buffer (encoded in uint8)

const image = await tf.node.decodeGif(pic.data)     //Decode the GIF using tensorflow

const prediction = await model.classifyGif(image);     //Classify the GIF (This is where the error is thrown)
```

Can anyone please help me out? Is there anywhere I can find sample code to GIF classification? Thank you in advance.

**Comment by GantMan** [comment]
Pinging @YegorZaremba  -  But I'll see about taking a look next week if he doesn't get a chance to look at this.

I should def include a node sample for gifs in the examples folder.

**Comment by edsumpena** [comment]
That sounds great. Thank you for your quick response!

**Comment by YegorZaremba** [comment]
Hi @edsumpena Here is test for `classifyGif` https://github.com/infinitered/nsfwjs/blob/master/__tests__/classifyGif.ts#L43

According to error https://github.com/nsfw-filter/gif-frames/blob/master/gif-frames.js#L45, It looks like your `url: gif` is empty https://github.com/infinitered/nsfwjs/blob/master/src/index.ts#L208

could you pls `debug/console.log` this  for me
```
const image = await tf.node.decodeGif(pic.data)  
console.log(Buffer.isBuffer(image))
```

**Comment by edsumpena** [comment]
Hi @YegorZaremba, I have run the log command. It returns "false".

**Comment by YegorZaremba** [comment]
@edsumpena I think you should skip decoding gif by tenserflow and pass buffer as is. We will improve this step for Node.js https://github.com/infinitered/nsfwjs/issues/431#issuecomment-716212203

This code also runs in browsers and they don't have some Node.js stuff. I plan to do separate logic in this lib for browsers and Node.js in the future

**Comment by edsumpena** [comment]
I have run the code without tf.node.decodeGif(pic.data) and it works. Thank you for your help!
