### ISSUE TITLE
Quantized model doesn't detect porn/hentai

### ISSUE THREAD

**Issue by link-discord** [infinitered/nsfwjs#451]
I am using the latest release of the nsfw detection model and when I tried the quantized version it just didn't detect any nsfw images at all while the normal model did

**Comment by GantMan** [comment]
Can you specify what size/link to the model you're using?  Maybe email me the images that it is failing on?

Are you sure this is for all NSFW images?  Or maybe just a few from your testing?

**Comment by GantMan** [comment]
Can you provide the failing issues?

**Comment by LINKdiscordd** [comment]
This is for all nsfw images
also its the x244 size one

I have put the  models that I use in my own repo called nsfwjs_model

**Comment by GantMan** [comment]
I just google image searched for pornographic and sexual images.   Then dragged them onto https://nsfwjs.com/ and they all were detected.

**Comment by LINKdiscordd** [comment]
But those models are not the quantum versions
My testings failed with quantum versions of the latest mobilenet x244 model
