### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by conver4y** [infinitered/nsfwjs#456]
Hey, I want to make sure that you've read my emails xD (from ray@blob-project.com)
I want to say, can we work together to see how far this improvement can go?
Thanks :)

**Comment by GantMan** [comment]
Sorry, I haven't seen any emails from you.

**Comment by conver4y** [comment]
That's really weird, let me resend it from **blobdevelopment@gmail.com**

**Comment by GantMan** [comment]
I got your email from your gmail account.   Closing this ticket.
