### ISSUE TITLE
[React] Cannot call a class as a function error in production build

### ISSUE THREAD

**Issue by amanvishnani** [infinitered/nsfwjs#457]
GitHub Repo: https://github.com/amanvishnani/firegram
Live URL: https://firegram-aman.web.app/

I get the following error on the production build however not on the Development build. Not sure what is causing this issue.
![image](https://user-images.githubusercontent.com/8425802/103568346-c8299d80-4e9b-11eb-926c-55c2b2de8383.png)

Can someone please help me out what's the issue here?

**Comment by GantMan** [comment]
@amanvishnani - is your GitHub repo private?

**Comment by amanvishnani** [comment]
@GantMan sorry about that, just made it public. Try now.

**Comment by GantMan** [comment]
Couple of notes:

Don't use `var` here.   It willl hoist and possibly cause issues with your useState
https://github.com/amanvishnani/firegram/blob/a9ac785a6ea2af9d78cd692bfde72b0bb882a007/src/hooks/useNsfw.js#L12
Try to stay away from using `var` anytime you can, instead use `let`.

Also, I'm not sure if my hook knowledge is limited, but what's stopping your second useEffect from firing before your first useEffect is complete?

Just a few things I noticed, but I'm not sure why it's calling a class.

**Comment by amanvishnani** [comment]
@GantMan the dependency array in the second useEffect tells it to only run when either `model` or `imageElement` is changed.

**Comment by GantMan** [comment]
But doesn't that run on the first time setting it?  My useEffect knowledge is always sticky.   Hah, I usually have to fiddle for 10 minutes to get it right :D   

Is the issue the model code 100%?  Have you tried switching NSFWJS out with any old object?

**Comment by amanvishnani** [comment]
Yes, although it is called for the initial values which are `null` and the if-condition will not run the code for the first time. 

I have tried with the v2.2.0 only. Did not try old models or previous versions. Not sure what is causing the issue when the build changes from Dev-build to Prod-build.

**Comment by GantMan** [comment]
I just found this:   https://github.com/tensorflow/tfjs/issues/3384

Take a look at the webpack.confi.js adjustment they recommend.

**Comment by amanvishnani** [comment]
Downgrading tfjs to 1.7.4 worked for me. Thanks.
