### ISSUE TITLE
False positive drawing

### ISSUE THREAD

**Issue by link-discord** [infinitered/nsfwjs#459]
![SPOILER_Matou_shinji-1-67-1.png](https://user-images.githubusercontent.com/50463727/103897058-3f0ca380-50f3-11eb-9578-8fad802bdb3f.png)

**Comment by LINKdiscordd** [comment]
The ai classify's this as hentai

**Comment by GantMan** [comment]
Which model did you use?    I'm dragging the image to NSFWJS.com and can't reproduce with the 90% mode or the 93% model.

![2](https://user-images.githubusercontent.com/997157/103913570-4bcad080-50ce-11eb-989b-40278c4ec53d.jpg)
![1](https://user-images.githubusercontent.com/997157/103913574-4c636700-50ce-11eb-966d-63b200faf26e.JPG)

**Comment by LINKdiscordd** [comment]
I used the 93% one
I set the jpg quality of images to 60 before scanning them using nsfwjs

**Comment by GantMan** [comment]
Can you provide the image you used?

And yes, false positives will happen.

**Comment by LINKdiscordd** [comment]
![SPOILER_Matou_shinji-1-67-2.jpg](https://user-images.githubusercontent.com/50463727/103941650-75681400-512f-11eb-8b88-8b594031607c.jpg)

**Comment by LINKdiscordd** [comment]
for whatever reason I don't have this false positive on the website while I do on my code

maybe its because I use tf prod mode

**Comment by LINKdiscordd** [comment]
From my testings, I have noticed that this issue is with the latest released model from the nsfwjs_model repo
when I used a previous release it didn't have this false positive

**Comment by GantMan** [comment]
@TechnikEmpire - would know what's up.

https://github.com/TechnikEmpire

**Comment by TechnikEmpire** [comment]
@LINKdiscordd link directly to the model you pulled and I'll check it out to see if I can repro.

**Comment by TechnikEmpire** [comment]
Just to be clear this could very well be a false positive. Latest models were trained by me with a vastly different data set than previous models. So imo such "bugs" can be expected, if they're defined simply by comparing against previous models. 

There will always be a margin of error. Even whether we get 70% or 99% "accuracy", those numbers only apply to the dataset we trained and tested on, not the billions of images in existence.

I'm still happy to verify this though if you link to it. I'm asking for a link so there's no error in verifying.

**Comment by LINKdiscordd** [comment]
https://github.com/GantMan/nsfw_model/releases/download/1.2.0/mobilenet_v2_140_224.1.zip

Its the model from the web model folder which has this false positive

**Comment by TechnikEmpire** [comment]
I can confirm that this is just a false positive.

**Comment by TechnikEmpire** [comment]
With relatively low confidence I might add, but still a false positive. 57% confidence.
