### ISSUE TITLE
UnhandledPromiseRejectionWarning: FetchError: request to https://s3.amazonaws.com/ir_public/nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/model.json failed, reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Anishvish** [infinitered/nsfwjs#464]
(node:19904) UnhandledPromiseRejectionWarning: FetchError: request to https://s3.amazonaws.com/ir_public/nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/model.json failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (D:\Learning\demo\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without 
a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by GantMan** [comment]
Is it working now?  It seems https://s3.amazonaws.com/ir_public/nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/model.json is loading fine

**Comment by Anishvish** [comment]
Hi Infinitered/Nsfwjs,

Thanks for response, Still i am getting the same issue for both the node js
code which is present in the documentation. Few days ago i have tried the
same code it was running but now it's not running

(node:19896) UnhandledPromiseRejectionWarning: FetchError: request to
https://s3.amazonaws.com/ir_public/nsfwjscdn/TFJS_nsfw_mobilenet/tfjs_quant_nsfw_mobilenet/model.json
failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous>
(D:\Learning\demo\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19896) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function
without
a catch block, or by rejecting a promise which was not handled with
.catch(). To terminate the node process on unhandled promise rejection, use
the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 1)
(node:19896) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the
 Node.js process with a non-zero exit code.

[image: image.png]

Thanks,
Anish

**Comment by dyaskur** [comment]
it seems like your internet change IP of aws CDN, try use vpn or other network

**Comment by fangmuke** [comment]
The master branch has modified the default URL.

**Comment by GantMan** [comment]
Correct, the new URL is a CDN and much faster.

**Comment by Anishvish** [comment]
Thanks guys, 
i found the solution basically antivirus was blocking to access the aws url from local. after making disable it's working
