### ISSUE TITLE
Question: what kind of this string

### ISSUE THREAD

**Issue by sinkaroid** [infinitered/nsfwjs#468]
sir, ty for this beautiful modules, i wanna ask a bit
i've using nodejs and return:
```json
[
  { className: 'Hentai', probability: 0.998166024684906 },
  { className: 'Porn', probability: 0.0016352280508726835 },
  { className: 'Drawing', probability: 0.00019833433907479048 },
  { className: 'Sexy', probability: 4.824803454539506e-7 },
  { className: 'Neutral', probability: 5.4902471902096295e-8 }
]
```
**0.998166024684906** what kind of this one? how can i convert `probability` value into percent instead or make it more readable?  
i tried it decimal into percent but the result is totality wrong. thankyou so much

**Comment by GantMan** [comment]
You can multiply probability by 100 to get percent.  Then you can round it.

**Comment by sinkaroid** [comment]
very cool gantman
