### ISSUE TITLE
Doesn't work in Typescript

### ISSUE THREAD

**Issue by LINKdiscordd** [infinitered/nsfwjs#496]
When trying to import NSFWJS and load a model I get an error saying that the load function doesn't exist even though the ide shows me that the load function does exist

code
```ts
import nsfw from 'nsfwjs'

nsfw.load(MODEL_URL, { type: graph })
```

error
```sh
TypeError: Cannot read property 'load' of undefined
```

**Comment by LINKdiscordd** [comment]
I also can't use type option unless I do a comment to supress the error when using the load function

**Comment by GantMan** [comment]
try `import * as nsfwjs from 'nsfwjs'`

**Comment by LINKdiscordd** [comment]
has worked
