### ISSUE TITLE
tensorflow .pb model wanted

### ISSUE THREAD

**Issue by DaiKiQi** [infinitered/nsfwjs#50]
I have found some nsfw's trained model or Demo, but yours perform best.
Could you upload the trained .pb model to help me develop my java Demo?
Thanks a lot.

**Comment by GantMan** [comment]
Hiya!  Yup!!!

The training code and `.pb` + others are located here:
https://github.com/GantMan/nsfw_model

Thanks so much for your kind words.  Feel free to let me know how it works for you, as I haven't tested the .pb yet.

**Comment by GantMan** [comment]
Closing because question is moved to https://github.com/infinitered/nsfwjs/wiki/FAQ:-NSFW-JS

**Comment by sodagreat** [comment]
> Hiya! Yup!!!
> 
> The training code and `.pb` + others are located here:
> https://github.com/GantMan/nsfw_model
> 
> Thanks so much for your kind words. Feel free to let me know how it works for you, as I haven't tested the .pb yet.

I have compared the results between pb and tensorflowjs , the pb model and keras model seems not working, much worse than the js demo
