### ISSUE TITLE
False Positive Drawing

### ISSUE THREAD

**Issue by link-discord** [infinitered/nsfwjs#513]
![DvYY8qbXgAAMi62.jpeg](https://user-images.githubusercontent.com/50463727/117496130-e51fcb80-af76-11eb-82be-37411380d1fb.jpeg)

**Comment by LINKdiscordd** [comment]
Model Used is the latest release from the nsfw model repo

**Comment by LINKdiscordd** [comment]
Prediction Results

Label: Hentai
Probability: 70%

**Comment by GantMan** [comment]
Thanks for sharing.  We'll add this to the data.
