### ISSUE TITLE
Many False Positives

### ISSUE THREAD

**Issue by EvEloBE** [infinitered/nsfwjs#520]
Hello. today i tried to implement nsfwjs into my discord bot, but im getting many false positives. 
This is my first time using tenserflow.

My problem is that the model marks almost everything as "Drawing" with 30-70% Probability. At first i didn't load a model but tried loading all of these models after seeing the results were wrong:
https://github.com/GantMan/nsfw_model/releases/tag/1.1.0   (when using this model i also tried setting its type to "graph", but the false results continued )
https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model
as well as one more model i cannot find the link of.
All of these models gave very similar false positives.

This is my code 
```
const nsfwjs = require('nsfwjs');
const tf = require('@tensorflow/tfjs-node'); // Tried with @tensorflow/tfjs and @tensorflow/tfjs-node-gpu as well
const fetch = require('node-fetch');

tf.enableProdMode(); // Read to do this here https://github.com/infinitered/nsfwjs#production but tried running without doing 
// it as well

class NSFWHandler {
  model = null;

  constructor() {
    this.#loadModel();
  }

  async #loadModel() {
    return (this.model = await nsfwjs.load());
  }

  async #formatData(attachment = null) {
    if (!attachment?.url || !attachment?.width || !attachment?.height) return;

    // Fetch image from url and save as buffer
    const imageBuffer = await fetch(attachment.url).then((res) => res.buffer());

    // Im passing this in this format because a error notified me i can pass data in this format
    return { data: imageBuffer, height: attachment.height, width: attachment.width };
  }

  async classifyImage(attachment) {
    if (!this.model) return console.log('NO MODEL');

    const formattedData = await this.#formatData(attachment);

    const classification = await this.model.classify(formattedData);

    return { ...classification, imageHash };
  }
}

module.exports = NSFWHandler;

```
I think the data format i pass in could be problematic, but im new to tenserflow and this was the only way it worked.
As a test i compared the results of 10 pictures both nsfw and sfw between my implementation and https://nsfwjs.com/ results with the site always scoring perfectly.
My implementation results were: Drawing: 80%
Website results for the same picture were: Sexy: 60%

**Comment by GantMan** [comment]
ahhh, I see you're using node.   I agree, it's an issue with how you're passing the images into the the model.

Can you try converting the images to a 3D Tensor and then passing them in to classify?   

BTW, if you're new, I have lots of sample code for converting images to Node.js tensors in my book source code:  https://github.com/GantMan/learn-tfjs

**Comment by EvEloBE** [comment]
Thanks. Seems to work way better, but the results are still not as confident as the results i get from the website. Does nsfwjs by default use a different model than the site, and if yes could i get it liked if it's public?

**Comment by GantMan** [comment]
The website has 3 different models
![image](https://user-images.githubusercontent.com/997157/122687805-fb5bb100-d1dd-11eb-9a55-0ba03231c55a.png)

You can choose whichever model you want most and grab it here for local hosting:  https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public

**Comment by GantMan** [comment]
Since this has been sitting for a week, I'm going to close this issue, let me know if you've got the model you want or have any further questions.

**Comment by EvEloBE** [comment]
Sorry forgot to close it. And yes it works perfectly now. Thanks.
