### ISSUE TITLE
Can webp image be detected ?

### ISSUE THREAD

**Issue by ldnvnbl** [infinitered/nsfwjs#523]
Someone can help me, how to use nsfwjs detect webp image, thanks

**Comment by GantMan** [comment]
Hiya @ldnvnbl - yes it does work with webp!   I noticed I forgot to add that option on NSFWJS.com - so I'll be adding it now.

**Comment by GantMan** [comment]
I've updated the site.  For posterity, if anyone wants to check using a webp file, just throw 
https://file-examples-com.github.io/uploads/2020/03/file_example_WEBP_50kB.webp
into NSFWJS.com

**Comment by GantMan** [comment]
Does that answer your question?  On web you'd do it the same way you detect any other image.

Are you needing to detect on a node server?

**Comment by ldnvnbl** [comment]
@GantMan I detect on node server

**Comment by GantMan** [comment]
You'll need to use something like this: https://www.npmjs.com/package/webp-converter

**Comment by ldnvnbl** [comment]
@GantMan my original image is webp, you means I should convert it to webp and then detect it ?

**Comment by GantMan** [comment]
woops.  I meant convert it to a different image then detect.

If you want it built into TFJS, you should open a ticket asking for node webp to tensor here:  https://github.com/tensorflow/tfjs/issues

**Comment by ldnvnbl** [comment]
> woops. I meant convert it to a different image then detect.
> 
> If you want it built into TFJS, you should open a ticket asking for node webp to tensor here: https://github.com/tensorflow/tfjs/issues

got it, thank you very much, you are so nice
