### ISSUE TITLE
Unexpected errors are thrown if image width and height is not specified

### ISSUE THREAD

**Issue by roerohan** [infinitered/nsfwjs#525]
When you try to run `model.classify(image)`, where `image` is of type `HTMLImageElement`; if the dimensions (width and height) of the image are not specified, the function throws unexpected errors, one of which is as follows:

```
DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded.
```

This is resolved if you make a new `Image` object with a width and height that you specify (`200` in the following example), and you set `newImg.crossOrigin` to `anonymous`. A similar code snippet is also used in the chrome extension [NSFW Filter](https://github.com/nsfw-filter/nsfw-filter/), yet there is no mention of it on the README of this repo.

https://github.com/nsfw-filter/nsfw-filter/blob/2abc417c4a840ed53a7b0cf060c3867d54265779/src/background/Queue/LoadingQueue.ts#L42-L50

```ts
// `image` is the original `HTMLImageElement` that is supposed to be classified
// `newImage` is `image` but with width and height specified (to 200, 200 in this case)

const newImg = new Image(200, 200);
newImg.crossOrigin = 'anonymous';
newImg.src = image.src;
model.classify(newImg)
```

Without the above modification, the image classification is inconsistent, i.e, it fails sometimes and succeeds sometimes for the same exact image (I've tested this on Google Images). It might be because the images contain too many pixels, I was not able to figure out why the error occurred randomly; but adding the above snippet fixed it. There should probably be a mention of this on the README of the repo or a fix that resolves the issue entirely.

**Comment by GantMan** [comment]
Interesting.  A couple thoughts come to mind.

The most likely issue is that there's a security issue where the `src` of the image is cross-origin.  By using the `Image` tag, you're effectively making a local copy and getting around `tainted canvases` issues.

That doesn't explain how it sometimes works and sometimes doesn't though.   That sounds more like a race-condition.   So maybe you're calling `classify` before the image is fully loaded?  I'd have to see the code to be sure.

**Comment by roerohan** [comment]
@thebongy could you please post the code snippet in a comment?

**Comment by thebongy** [comment]
I'll paste the relevant part of the code here.
We basically had a content script in a chrome extension which did the following:

```typescript

let model: nsfwjs.NSFWJS;

nsfwjs.load('<redacted private url>').then((loaded) => {
  model = loaded;
});


window.onload = async () => {
   const images = [...document.querySelectorAll('img')];
    for (const image in images) {
      try {
        console.log(await filterImage(images[image], 0.5));
        await sleep(50);
      } catch (err) {
        console.log(err);
        // Blank
      }
    }
}

export default async function filterImage(
  image: HTMLImageElement, threshold: Number,
): Promise<FilterResult> {
  const width = image.clientWidth;
  if (width < 50) {
    return {
      filter: false,
      reason: 'The image is too small',
    };
  }
  const newImg = new Image(200, 200);
  newImg.crossOrigin = 'anonymous';
  newImg.src = image.src;
  const result = await scanImage(newImg);
  const highest = result[0];

  if (highest.className === 'Neutral' || highest.className === 'Drawing') {
    return {
      filter: false,
      reason: 'The image is neutral.',
    };
  }

  if (highest.probability < threshold) {
    return {
      filter: false,
      reason: 'The image is below the given threshold.',
    };
  }

  return {
    filter: true,
    reason: `The image has ${highest.className} content which is over the configured threshold.`,
  };
}


async function scanImage(element: HTMLImageElement) {
  while (!model) {
    // eslint-disable-next-line no-await-in-loop
    await sleep(1000);
  }
  return model.classify(element);
}

```

What we observed was that the same code, when the lines
```typescript
const newImg = new Image(200, 200);
  newImg.crossOrigin = 'anonymous';
  newImg.src = image.src;
```
weren't present, and we just directly processed the input image, we would sometimes get the error posted originally on this issue (Tainted canvases may not be loaded.) . But constructing a new smaller intermediate image always made the library work.

**Comment by GantMan** [comment]
This seems to be a bug with TFJS
https://github.com/tensorflow/tfjs/issues/322

It's also been identified here: https://stackoverflow.com/questions/57662313/requested-texture-size-0x0-is-invalid-error-when-i-am-loading-image-in-browse

This didn't used to be a bug.


However, the error you're getting seems to actually be a crossDomain error.   Because you're loading an image from a different website.  So you'll need to make a local copy.


You can test all 4 possible situations with this codesandbox I created here: 
* switch between `img1` and `img2` for local and remote. 
* switch line 14 and 15 for image resize on and off

https://codesandbox.io/s/nsfwjscrossoriginnsizecheck-epu3w?file=/src/index.js

**Comment by thebongy** [comment]
I see, thank you for verifying!

For now the  intermediate image solution works for us, we'll update on this thread if we find out anything new about the issue :)

**Comment by cdanwards** [comment]
@thebongy glad that you were able to find a solution that works for you. Let us know if you have any more problems like this in the future, but for now we're going to close this issue.
