### ISSUE TITLE
Cannot see the whole dropdown on nsfwjs.com

### ISSUE THREAD

**Issue by bokub** [infinitered/nsfwjs#527]
Just FYI, on https://nsfwjs.com, it's impossible to see the bottom of the dropdown because the page cannot be scrolled.

![image](https://user-images.githubusercontent.com/17952318/123605825-8b13e780-d7fc-11eb-80ce-cf0350c08f93.png)

Have a good day

**Comment by GantMan** [comment]
fixed and deployed
