### ISSUE TITLE
False Positive: women eating banana

### ISSUE THREAD

**Issue by 404hz** [infinitered/nsfwjs#560]
Hi Gant, NSFW JS will fail with pictures of women eating banana!

just a doing a simple google search: 
https://www.google.com/search?q=woman+eating+banana

... and some examples:
https://image.shutterstock.com/image-photo/young-woman-eating-banana-260nw-3106254.jpg
https://thumb.mp-farm.com/89598622/preview.jpg
https://st2.depositphotos.com/1012146/6473/i/950/depositphotos_64738027-stock-photo-girl-eating-a-banana.jpg
https://image.shutterstock.com/image-photo/woman-eating-banana-260nw-514825333.jpg

as what I know, eating a (real) banana is not porn or nudity!

**Comment by GantMan** [comment]
I'll add these to the training data.  Thanks for the find.
