### ISSUE TITLE
Where is the latest model?

### ISSUE THREAD

**Issue by davidsarkany** [infinitered/nsfwjs#564]
Hi!

Where I find the latest models?
This models updated 2-3 year ago: https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public

**Comment by GantMan** [comment]
There hasn't been any significant updates to the models to re-release them.  Most of the updates have been to the code.

There might be a mobilent v3 model at some point.  For now, we're looking to add in a voting classifier to help merge existing models into a higher accuracy option, but none of this is under active development beyond support for updates.
