### ISSUE TITLE
Question on how to add more classifications on this model

### ISSUE THREAD

**Issue by Staminax** [infinitered/nsfwjs#565]
Hi, can I sort of "upgrade" this model by adding one more category of classification? If so, how could I do it?
Thank you!

**Comment by GantMan** [comment]
Great question.

To take a trained model and train more data on top of it, you can do transfer learning.  I actually cover how to do transfer learning in my book, in chapter 11 I think (https://infinite.red/learn-tensorflowjs).   However, it's not a straightforward process.  It takes time and skill.

It really depends on the data, and then you have to test it.   What categories are you thinking of adding?

**Comment by Staminax** [comment]
> Great question.
> 
> To take a trained model and train more data on top of it, you can do transfer learning. I actually cover how to do transfer learning in my book, in chapter 11 I think (https://infinite.red/learn-tensorflowjs). However, it's not a straightforward process. It takes time and skill.
> 
> It really depends on the data, and then you have to test it. What categories are you thinking of adding?

gun detection

**Comment by GantMan** [comment]
I would start a separate model and train it on all kinds of weapons.  I bet there are datasets out there to help get you started!

I'd recommend grabbing a few courses or books on training models and then use NSFWJS as a good example on how to glue the model into a JavaScript API.

**Comment by Staminax** [comment]
> I would start a separate model and train it on all kinds of weapons. I bet there are datasets out there to help get you started!
> 
> I'd recommend grabbing a few courses or books on training models and then use NSFWJS as a good example on how to glue the model into a JavaScript API.

Thanks for the attention and replies. I'll take a look on it for sure. Appreciate it.

**Comment by GantMan** [comment]
you're very welcome!
