### ISSUE TITLE
Support TensorflowJS 1.x

### ISSUE THREAD

**Issue by GantMan** [infinitered/nsfwjs#61]
Currently we are using Tensorflow 0.15.x, but we should support latest tensorflow.

Update and fix to work with latest.

**Comment by xilaraux** [comment]
I can take it.

**Comment by GantMan** [comment]
Sorry, @xilaraux - I just knocked this one out.  Great minds think alike!

**Comment by GantMan** [comment]
I wouldn't mind a review!   https://github.com/infinitered/nsfwjs/pull/78
