### ISSUE TITLE
nodejs execution

### ISSUE THREAD

**Issue by pguli** [infinitered/nsfwjs#63]
Hello! Is possibile to use with nodejs in a backend environment? Because i have seen only client-side javascript example.

Thank you

**Comment by GantMan** [comment]
Hiya!  Someone seems to have done this in #25 

Please let me know if it works for you.  I'm hoping to add a Wiki section on this, and your experience would be most helpful. 

Gonna close this ticket, so update us over at #25 if you can 👍
