### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by MicroCBer** [infinitered/nsfwjs#634]
![QQ图片20220627034452](https://user-images.githubusercontent.com/66859419/175831249-05bb56ba-2b7b-42ab-8236-b033f6e32af9.jpg)
![2AU$ULA9USGQ8GF~I1PDWUC](https://user-images.githubusercontent.com/66859419/175831325-046eba11-2cc8-40e4-b55b-e987c7784b2b.jp
![QNVL05K KIRB1 T `O@OUTD](https://user-images.githubusercontent.com/66859419/175831331-4e42263e-1e3d-4aba-b96b-a03138546fe0.jpg)
g)
![~BVJB}V$}K51WO3EB(U7W1C](https://user-images.githubusercontent.com/66859419/175831332-9dfa05ba-317f-44c4-886d-105a54a6a7d8.jpg)

**Comment by GantMan** [comment]
Will be added to training data, thank you!
