### ISSUE TITLE
@tensorflow/tfjs-node is depreciated?

### ISSUE THREAD

**Issue by qozle** [infinitered/nsfwjs#636]
It looks like tfjs-node has been archived.  Is it still ok to use?  Should this project switch to @tensorflow/tfjs?

**Comment by GantMan** [comment]
I just pulled up the docs, and I don't see anything about archived.  Where are you looking?
https://github.com/tensorflow/tfjs/tree/master/tfjs-node

**Comment by GantMan** [comment]
ah good!  Reopen if I can help.
