### ISSUE TITLE
how can i switch to using the 93% Accurate version?

### ISSUE THREAD

**Issue by NightCode5555** [infinitered/nsfwjs#652]
im trying to find a way to use the 93% accurate version like shown in the website
![image](https://user-images.githubusercontent.com/88519104/184683565-c1c2024b-b7cc-4e9a-9189-259b275f30de.png)

the reason for it is it keeps detecting this image as hentai with a score of 90% on my project, however when i tried using the 93% on the website it classifies it as drawing
![image](https://user-images.githubusercontent.com/88519104/184682977-043aa570-170f-4022-8ca5-d4bc9d19906d.png)

Any help is appreciated

**Comment by GantMan** [comment]
You can download it here: https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/quant_mid

Then point the NSFWJS library at your hosted model when loading:  https://github.com/infinitered/nsfwjs#load-the-model

**Comment by NightCode5555** [comment]
so i do something like this?
```js
model = await nsfw.load('/model', {type: 'graph'})
```

**Comment by cdanwards** [comment]
@NightCode5555 are you still having any issues here?
