### ISSUE TITLE
Can we get the SavedModel of the nsfwjs json model ?

### ISSUE THREAD

**Issue by Edouard127** [infinitered/nsfwjs#671]
I don't have the required tensorflow & python knowledge for it, and I don't think I'm the only one that wants it

**Comment by GantMan** [comment]
You're looking for the .h5 file?  I think you can convert this pretty easy, but just making sure.

**Comment by Edouard127** [comment]
> You're looking for the .h5 file? I think you can convert this pretty easy, but just making sure.

Yes I'm talking about the .h5 file
I couldn't find a way to convert it back

**Comment by Edouard127** [comment]
@GantMan I tried before to convert the h5 to pb, using some programs, and I never succeeded to convert it in pb
If you have the pb on your side I would be very grateful if you could make it public

**Comment by GantMan** [comment]
Unfortunately, I had a computer crash, so I only have an outdated h5 :( I can provide that but it's not as good as the current one.

**Comment by Edouard127** [comment]
> Unfortunately, I had a computer crash, so I only have an outdated h5 :( I can provide that but it's not as good as the current one.

All I need is a saved_model, I've been trying for 2 days to get the nsfw_model model working, but the results are always wrong, maybe I'm processing the image wrongly

**Comment by GantMan** [comment]
Here are two old h5 files.  I can't speak to how accurate they are.

https://nsfwdetector.s3.amazonaws.com/private/nsfw.299x299.h5
https://nsfwdetector.s3.amazonaws.com/private/february_2019_nsfw.299x299.h5

Man, that sucks having issues with the model for 2 days!  I wish you luck.

**Comment by Edouard127** [comment]
I'm talking about the saved_model file .pb, not the .h5 ones

**Comment by GantMan** [comment]
This is all I have for ya bud
https://nsfwdetector.s3.amazonaws.com/private/nsfw.299x299.pb

**Comment by Edouard127** [comment]
Alright thanks 👍

**Comment by FurkanGozukara** [comment]
how did you load [nsfw.299x299.pb](https://nsfwdetector.s3.amazonaws.com/private/nsfw.299x299.pb) locally? can you share code? i need to locally classify images
