### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by GantMan** [infinitered/nsfwjs#68]
There are tests.  Let's add CI for verification on PRs

**Comment by xilaraux** [comment]
I can take it.

**Comment by GantMan** [comment]
Awesome @xilaraux - looking forward to it.  Let me know what you need from me.

**Comment by GantMan** [comment]
Need any help @xilaraux ?

**Comment by xilaraux** [comment]
I was a little bit busy, will complete it soon.
Thx for asking.

**Comment by xilaraux** [comment]
@GantMan Here it goes: https://github.com/infinitered/nsfwjs/pull/77

**Comment by GantMan** [comment]
Merged and it looks good!  Will add you to the contributors now.
