### ISSUE TITLE
npm modules conflict 

### ISSUE THREAD

**Issue by Besufikad17** [infinitered/nsfwjs#692]
Hey there, I followed the installation steps listed in the readme file but I am getting this npm error is there a way to fix it ?

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: nsfwjs@2.2.0
npm ERR! Found: @tensorflow/tfjs@3.21.0
npm ERR! node_modules/@tensorflow/tfjs
npm ERR!   @tensorflow/tfjs@"^3.21.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @tensorflow/tfjs@"^1.7.4" from nsfwjs@2.2.0
npm ERR! node_modules/nsfwjs
npm ERR!   nsfwjs@"^2.2.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @tensorflow/tfjs@1.7.4
npm ERR! node_modules/@tensorflow/tfjs
npm ERR!   peer @tensorflow/tfjs@"^1.7.4" from nsfwjs@2.2.0
npm ERR!   node_modules/nsfwjs
npm ERR!     nsfwjs@"^2.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Melak12** [comment]
use a combination of "@tensorflow/tfjs": "^3.18.0" with "nsfwjs": "^2.4.2".

**Comment by cdanwards** [comment]
Following up here, @Besufikad17 did this solution fix your issue?

**Comment by Besufikad17** [comment]
Nope the installation works when i used nsfwjs and tensorflowjs version specified by @Melak12 but when i try to run npm audit fix it throws the above error
