### ISSUE TITLE
Nice Feature Idea - Scrub GIF

### ISSUE THREAD

**Issue by GantMan** [infinitered/nsfwjs#79]
It would be pretty cool if when you scubbed the victory bar for a GIF, the associated GIF frame was shown.  This can happen by having an option passed in for a reference to the SuperGIF and then using `move_to(index)`.  If you don't want the supergif, it's set to NULL in memory like it is currently.

I'd love to see why a particular frame is misclassified!

**Comment by GantMan** [comment]
@xilaraux - sorry I took your last ticket, would you want this one?

**Comment by xilaraux** [comment]
@GantMan don't be sorry :) 
I can handle it, but it will take a while for me.

**Comment by GantMan** [comment]
Awesome! Off the top of my head here's a simple implementation:

* [`classifyGif`](https://github.com/infinitered/nsfwjs/blob/76948557feee91a7f0df097ac6f7a98968ef6485/src/index.ts#L153-L188) takes options.  One option is an object to store the SuperGif 
* When you use this option, [SuperGif is not set to null in `classifyGif`](https://github.com/infinitered/nsfwjs/blob/76948557feee91a7f0df097ac6f7a98968ef6485/src/index.ts#L183)
* The web page now has a reference tot he SuperGif
* [Victory Bar](https://formidable.com/open-source/victory/docs/victory-bar) Charts can have an `onHover` event described in their docs.  Add that to the existing [GifBar](https://github.com/infinitered/nsfwjs/blob/76948557feee91a7f0df097ac6f7a98968ef6485/example/nsfw_demo/src/components/GifBar.js#L48-L74)
* The `onHover` calls the SuperGif [`move_to(i)`](https://github.com/buzzfeed/libgif-js) - I think plus 1 - check index off by one possibility here

**Comment by xilaraux** [comment]
You almost did it.
I will implement it. :) 
I don't understand one thing. Should the frame be displayed next to [this](https://github.com/infinitered/nsfwjs/blob/76948557feee91a7f0df097ac6f7a98968ef6485/example/nsfw_demo/src/components/GifBar.js#L51) text or somewhat separately?

**Comment by GantMan** [comment]
Hahahaha.

So I think if you call `GifReference.move_to(i)` the GIF they dropped will lock to that frame.  No need to show it anywhere.  Basically it will stop animating and move to that frame.  I think.... :)  Once you start experimenting it should be clear.  Then when you stop mousing over the graph, it would be cool if it went back to animating.

**Comment by GantMan** [comment]
@xilaraux - how goes it?

**Comment by xilaraux** [comment]
You can see the progress here - #83 
I want to propose to name SuperGif object as `gifControl` and `setGitControl` and prop in config. What do you think? 
Also, I have doubts about the way I am setting this object and saving if to the React state, but spoiling the window is not an option neither.
Looking forward to your review :) 
Sorry for the delay.

**Comment by GantMan** [comment]
Looks great, I updated your contributor status in the readme:  https://github.com/infinitered/nsfwjs/commit/5413bd0e8541e3bf555a355712ef0959d3e0f04e
