### ISSUE TITLE
Publish to npm out of sync

### ISSUE THREAD

**Issue by tylertyssedal** [infinitered/nsfwjs#815]
npm hasn't been published in over a year. 

The `package.json` on github has a `"@tensorflow/tfjs": "^4.0.0"`, while npm has `"@tensorflow/tfjs": "^3.18.0"`, despite being listed as the same version `2.4.2`.

**Comment by GantMan** [comment]
you're very right!  I need to update!  
Do you have an interest in becoming an npm publisher ?

**Comment by tylertyssedal** [comment]
Hey @GantMan. I'd be interested in helping out. 

I'll shoot you an email and we can discuss scope and whatnot.

**Comment by mazenchami** [comment]
@tylertyssedal thanks for opening this issue! we've updated `nsfwjs` to `v3.0.0`! ([npm](https://www.npmjs.com/package/nsfwjs/v/3.0.0) & [github](https://github.com/infinitered/nsfwjs/releases/tag/v3.0.0))
