### ISSUE TITLE
MobileNetV2Mid doesn't load

### ISSUE THREAD

**Issue by Chungmire** [infinitered/nsfwjs#843]
I can load regular MobileNetV2 by referencing the folder containing the json and shard files, but can't with v2Mid. I can load it with the .min.js method and then save it to IndexedDB, but when trying to load from IndexedDB it throws the same error as it does when trying to load it from path. I tried loading with and without { size: 299 } and saving with and without it.

Output is too many characters, view here:
https://pastebin.com/E04VhTYM

Starts with:  `Error: layer: Improper config format`
Ends with `'className' and 'config' must set.`

**Comment by GantMan** [comment]
That error tends to happen when you try to load a graph model with a layers model call, or a layers model call with a graph model.  

Maybe try `{ type: "graph" }`?

**Comment by Chungmire** [comment]
> That error tends to happen when you try to load a graph model with a layers model call, or a layers model call with a graph model.
> 
> Maybe try `{ type: "graph" }`?

This worked. Admittedly, this is something I should've tried but didn't because the docs were a bit unclear in this regard, making it seem as though MobileNetV2Mid didn't need to be loaded with the type specified and making it seem as though the type is saved when you save the model to IndexedDB. Below are the sections referenced here.


"Model MobileNetV2Mid - [299x299]
const model = nsfwjs.load("/path/to/different/model/", { size: 299 });"

"Model InceptionV3 - [Graph]
const model = nsfwjs.load("/path/to/different/model/", { type: "graph" });"

"Parameters:
optional URL to the model.json folder.
optional object with size property that your model expects."

**Comment by GantMan** [comment]
would LOVE a rewrite PR of the docs that's more clear!
 
 Please feel free to be added as a contributor with a lil Readme magic!
