### ISSUE TITLE
Where is the javascript code to put on the web-server?

### ISSUE THREAD

**Issue by bongobongo** [infinitered/nsfwjs#85]
About the nsfwjs we can read the following:
"A simple JavaScript library to help you quickly identify unseemly images; all in the client's browser."

So, where is the actual javascript that we can upload to our web-server, and then use on the client side, to "identify unseemly images"?
It would be nice if that particular javascript was easily accessible from this github page. That way it would be a lot quicker to implement in various web applications.

I have tested the demo page, which is to be found here: 
https://nsfwjs.com/
Have tested it with several images which contain e.g. various sexy and porn content. It works like expected. So far so good. But the javascript code used on that demo page, is not usable in my web-application.

So where is the actual javascript code that I can implement in my web-application?
Does this module require node.js to work?
What did I miss?

**Comment by GantMan** [comment]
One more note bongo!  I see you saying "web server" so if you're hosting with node (server side), you can use this library there as well.  See the FAQ:  https://github.com/infinitered/nsfwjs/wiki/FAQ:-NSFW-JS

**Comment by bongobongo** [comment]
Okay, but if nsfwjs is just plain client side javascript, then I do not understand why the javascript is not available here as it should be used on the client side. 
Do I need node.js to make this work or not?

Just using this line client side: 
import * as nsfwjs from 'nsfwjs'

gives this error in javascript: 
"Unexpected token *"

**Comment by GantMan** [comment]
ok good just client side JavaScript.

No need for node if you're hosting the files for client JS.

Is your JavaScript es6+?  Are you looking to use script tags?  It sounds to me like you need a non NPM example.

**Comment by GantMan** [comment]
Here, I've made the simplest possible example:  Please let me know if this helps.

https://github.com/infinitered/nsfwjs/blob/master/example/minimal_demo/index.html

Closing ticket.

**Comment by bongobongo** [comment]
This is getting closer to something I can use. 
The code you provided do work, but:
What I need to do now is to be able to call model.classify in a separate function. 
So I tried this:

const nsfwjs = require('nsfwjs')
const model = nsfwjs.load();

Then in function analyzeImage I put this code:

const img = new Image();
img.crossOrigin = 'anonymous';
img.src = 'http://localhost/atest-code/geocode/pixlab/images/35.jpg';
predictions = model.classify(img);
console.log('Predictions: ', predictions);

WHAT happens now is that I click a button which run the analyzeImage function, I get this error:
"model.classify is not a function"

So how do I use the "model.classify(img)" from within a function like this?
I would not like to load the model each time an image is classified, if possible to avoid.

**Comment by GantMan** [comment]
So the issue looks like scope.  

One way to keep a reference to a variable is to fasten it on your global window object. Like
“window.model = nsfwjs.load()”

And you can later access it with window.model

**Comment by bongobongo** [comment]
Thanks a lot for your help. 
It's working fine now.
