### ISSUE TITLE
Error: Could not load the model. Make sure you are importing the model.min.js bundle.

### ISSUE THREAD

**Issue by ChrisBechi** [infinitered/nsfwjs#863]
I have a Vite project and I'm getting the following error when installing the library in version: ^4.1.0. I followed the documentation but apparently Vite has some issues. Does anyone know how I can solve this?

nsfwjs.js?v=168f040f:67180 Uncaught (in promise) 
Error: Could not load the model. Make sure you are importing the model.min.js bundle.
    at nsfwjs.js?v=168f040f:67180:17
    at step4 (nsfwjs.js?v=168f040f:67073:18)
    at Object.next (nsfwjs.js?v=168f040f:67025:14)
    at nsfwjs.js?v=168f040f:67012:70
    at new Promise (<anonymous>)
    at __awaiter (nsfwjs.js?v=168f040f:66994:10)
    at loadModel (nsfwjs.js?v=168f040f:67158:10)
    at Module.<anonymous> (nsfwjs.js?v=168f040f:67212:22)
    at step4 (nsfwjs.js?v=168f040f:67073:18)
    at Object.next (nsfwjs.js?v=168f040f:67025:14)

**Comment by Anas-7** [comment]
Hi, did you find a fix for this? Currently facing the same issue

**Comment by liuyudaye** [comment]
When will this problem be fixed? I've encountered it too.

**Comment by stevecohenfr** [comment]
Same here with a Ionic/Angular project (only on production)

**Comment by atheless** [comment]
I am having the same issue in my Nuxt 3 (with spa mode) project. It throws an error right after this line:  `const model = await nsfwjs.load("MobileNetV2Mid");`

Any solutions? 


```js
nsfwjs.js?v=0f6cacb3:217 Uncaught (in promise) Error: Could not load the model. Make sure you are importing the model.min.js bundle.
    at nsfwjs.js?v=0f6cacb3:217:17
    at step (nsfwjs.js?v=0f6cacb3:110:17)
    at Object.next (nsfwjs.js?v=0f6cacb3:62:14)
    at nsfwjs.js?v=0f6cacb3:49:67
    at new Promise (<anonymous>)
    at __awaiter (nsfwjs.js?v=0f6cacb3:31:10)
    at loadModel (nsfwjs.js?v=0f6cacb3:195:10)
    at Module.<anonymous> (nsfwjs.js?v=0f6cacb3:249:22)
    at step (nsfwjs.js?v=0f6cacb3:110:17)
    at Object.next (nsfwjs.js?v=0f6cacb3:62:14)
```

**Comment by atheless** [comment]
Found a solution to my problem. 

Instead of this as per docs:
```js
const model = nsfwjs.load("/path/to/different/model/", { type: "graph" });
```

Use this one:
```js
 const model = await nsfwjs.load("/nsfw_models/inception_v3/", { size: 299 });
```

Same thing for `MobileNetV2Mid`. In fact options in source code appear differently compared to docs.
```js
const availableModels: ModelConfig = {
  MobileNetV2: { path: "mobilenet_v2", numOfWeightBundles: 1 },
  MobileNetV2Mid: {
    path: "mobilenet_v2_mid",
    numOfWeightBundles: 2,
    options: { type: "graph" },
  },
  InceptionV3: {
    path: "inception_v3",
    numOfWeightBundles: 6,
    options: { size: 299 },
  },
};
```  


If you are running a bundling issues with vite, just download `src` folder and save it locally, and import it like this:
```js
import * as nsfwjs from "@/utils/nsfwjs" // nsfwjs contain .ts and .js
```
