### ISSUE TITLE
Removing console.log

### ISSUE THREAD

**Issue by castilloedwin** [infinitered/nsfwjs#882]
Hey team good afternoon, is there a way to remove the console.log which is displayed when you call the nsfwjs.load function?

**Comment by GantMan** [comment]
hey hey!  Do you mean this warning when you're using the default model and not the hosted one?

https://github.com/infinitered/nsfwjs/blob/master/src/index.ts#L139

**Comment by castilloedwin** [comment]
Yeah that one @GantMan

**Comment by GantMan** [comment]
So we want to keep that warning. That message only displays if you are using the FREE model that we host.  To remove it, host your own copy of the model as specified in the Readme.

https://github.com/infinitered/nsfwjs?tab=readme-ov-file#host-your-own-model

**Comment by castilloedwin** [comment]
Thanks @GantMan I'll do that
