### ISSUE TITLE
Inconsistency between nsfw website and my project

### ISSUE THREAD

**Issue by castilloedwin** [infinitered/nsfwjs#888]
Hi team good evening, I think there's an inconsistency regarding the model, for example, on my project I'm using InceptionV3 and same model on https://nsfwjs.com and on the website it's more accurate than my project (I'm using the same test images) do you know what could be happening?

**Comment by GantMan** [comment]
That is VERY strange.  Have you tried running NSFWJS locally and then checking for mistakes?

**Comment by castilloedwin** [comment]
Yes I tried that @GantMan but for some reason, locally, I got an error of that model, the other ones work fine locally but they are less accurate

**Comment by castilloedwin** [comment]
Yeah totally sure, I'm calling the model.json but it throws an error, have you tried it with that model locally?

**Comment by GantMan** [comment]
can you supply the error?

**Comment by castilloedwin** [comment]
@GantMan 
![Screen Shot 2024-09-24 at 1 41 03 AM](https://github.com/user-attachments/assets/6cb3f7b7-6044-4317-ab03-b39c4dd11288)

mobilenet_v2 and mobilenet_v2_mid work fine locally

**Comment by GantMan** [comment]
ahhh you have to set the size parameter to 299

`const model = nsfwjs.load("/path/to/model/", { size: 299 });`

**Comment by castilloedwin** [comment]
Oh, it worked, thanks man @GantMan
