### ISSUE TITLE
Error when calling nsfwjs.load

### ISSUE THREAD

**Issue by lilyissillyyy** [infinitered/nsfwjs#902]
![firefox_IVZ34vojA3](https://github.com/user-attachments/assets/cc4744c8-9f06-4ca7-9455-fa238602175c)

Relevant code: https://github.com/dragonfire535/xiao/blob/master/structures/Tensorflow.js#L18-L22

**Comment by haZya** [comment]
Hey @dragonfire535 

This issue seems to be related to: https://github.com/tensorflow/tfjs/pull/8425

Try using an older version of `@tensorflow/tfjs-node` for now. Something like `4.10.0` should work.

**Comment by partha4u21** [comment]
use a lts version of node. use nvm to install a lts version and set it as default. it should work.
